import Foundation

// MARK: - Suggestion State
//
// Adapted from OpenClaw's `src/agents/subagent-lifecycle-events.ts`.
// Typed state machine for suggestion lifecycle.

/// State of a proactive suggestion as it moves through the dispatch pipeline.
enum SuggestionState: Equatable, Sendable {
    case pending
    case dispatched(channel: String)
    case seen
    case accepted
    case snoozed(until: Date)
    case dismissed
    case expired
    case chained(nextId: String)

    var isTerminal: Bool {
        switch self {
        case .accepted, .dismissed, .expired, .chained:
            return true
        default:
            return false
        }
    }
}

// MARK: - Suggestion Outcome

/// Outcome of an accepted suggestion's execution.
/// Mirrors OpenClaw's `SubagentRunOutcome` from `subagent-announce.ts`.
enum OutcomeStatus: String, Sendable {
    case ok
    case error
    case timeout
    case skipped
}

struct SuggestionOutcome: Sendable {
    let status: OutcomeStatus
    let error: String?
    let chainedSuggestionId: String?

    init(status: OutcomeStatus, error: String? = nil, chainedSuggestionId: String? = nil) {
        self.status = status
        self.error = error
        self.chainedSuggestionId = chainedSuggestionId
    }
}

// MARK: - Urgency Level

struct UrgencyLevel: Sendable, Equatable, Comparable {
    let score: Int
    let tier: Tier

    enum Tier: String, Sendable, CaseIterable {
        case critical
        case high
        case medium
        case low
    }

    init(score: Int) {
        self.score = max(0, min(100, score))
        if self.score >= 80 { self.tier = .critical }
        else if self.score >= 60 { self.tier = .high }
        else if self.score >= 40 { self.tier = .medium }
        else { self.tier = .low }
    }

    func adjusted(by multiplier: Float) -> UrgencyLevel {
        UrgencyLevel(score: Int(Float(score) * multiplier))
    }

    static func < (lhs: UrgencyLevel, rhs: UrgencyLevel) -> Bool {
        lhs.score < rhs.score
    }
}

// MARK: - Proactive Suggestion

/// A proactive suggestion generated by the engine.
struct ProactiveSuggestion: Identifiable, Sendable {
    let id: String
    let type: ProactiveSuggestionType
    let title: String
    let detail: String
    let prompt: String
    let icon: String
    var urgency: UrgencyLevel
    var state: SuggestionState
    let createdAt: Date
    var expiresAt: Date?
    var outcome: SuggestionOutcome?

    /// Chain definition: what suggestion to spawn after this one completes.
    var chainOnSuccess: ProactiveSuggestionType?
    var chainOnFailure: ProactiveSuggestionType?

    init(
        id: String = UUID().uuidString,
        type: ProactiveSuggestionType,
        title: String,
        detail: String,
        prompt: String,
        icon: String,
        urgency: UrgencyLevel,
        expiresAt: Date? = nil,
        chainOnSuccess: ProactiveSuggestionType? = nil,
        chainOnFailure: ProactiveSuggestionType? = nil
    ) {
        self.id = id
        self.type = type
        self.title = title
        self.detail = detail
        self.prompt = prompt
        self.icon = icon
        self.urgency = urgency
        self.state = .pending
        self.createdAt = Date()
        self.expiresAt = expiresAt
        self.chainOnSuccess = chainOnSuccess
        self.chainOnFailure = chainOnFailure
    }

    func withUrgency(_ newUrgency: UrgencyLevel) -> ProactiveSuggestion {
        var copy = self
        copy.urgency = newUrgency
        return copy
    }
}

// MARK: - Suggestion Lifecycle Manager

/// Manages suggestion state transitions, retry logic, and orphan cleanup.
/// Adapted from OpenClaw's `subagent-registry.ts`.
actor SuggestionLifecycleManager {

    private var suggestions: [String: ProactiveSuggestion] = [:]
    private var history: [ProactiveSuggestion] = []
    private let maxHistorySize = 200
    private let orphanExpirySeconds: TimeInterval = 3600
    private let maxAnnounceRetries = 3

    // MARK: - State Transitions

    func track(_ suggestion: ProactiveSuggestion) {
        suggestions[suggestion.id] = suggestion
    }

    func transition(id: String, to newState: SuggestionState) -> ProactiveSuggestion? {
        guard var suggestion = suggestions[id] else { return nil }
        suggestion.state = newState

        if newState.isTerminal {
            suggestions.removeValue(forKey: id)
            history.insert(suggestion, at: 0)
            if history.count > maxHistorySize {
                history = Array(history.prefix(maxHistorySize))
            }
        } else {
            suggestions[id] = suggestion
        }

        return suggestion
    }

    func setOutcome(id: String, outcome: SuggestionOutcome) -> ProactiveSuggestion? {
        guard var suggestion = suggestions[id] ?? history.first(where: { $0.id == id }) else { return nil }
        suggestion.outcome = outcome

        if suggestions[id] != nil {
            suggestions[id] = suggestion
        } else if let idx = history.firstIndex(where: { $0.id == id }) {
            history[idx] = suggestion
        }

        return suggestion
    }

    // MARK: - Query

    func activeSuggestions() -> [ProactiveSuggestion] {
        Array(suggestions.values).sorted { $0.urgency > $1.urgency }
    }

    func recentHistory(limit: Int = 20) -> [ProactiveSuggestion] {
        Array(history.prefix(limit))
    }

    func pendingCount() -> Int {
        suggestions.values.filter { $0.state == .pending }.count
    }

    // MARK: - Orphan Cleanup

    /// Clean up stale suggestions that never resolved.
    /// Mirrors OpenClaw's `reconcileOrphanedRun`.
    func cleanupOrphans() {
        let now = Date()
        let orphanIds = suggestions.filter { _, s in
            now.timeIntervalSince(s.createdAt) > orphanExpirySeconds && !s.state.isTerminal
        }.map(\.key)

        for id in orphanIds {
            _ = transition(id: id, to: .expired)
        }

        if !orphanIds.isEmpty {
            GRumpLogger.proactive.info("Cleaned up \(orphanIds.count) orphaned suggestions")
        }
    }

    // MARK: - Stats

    func acceptanceRate(for type: ProactiveSuggestionType? = nil) -> Float {
        let relevant = type == nil ? history : history.filter { $0.type == type }
        guard !relevant.isEmpty else { return 0 }
        let accepted = relevant.filter { $0.state == .accepted || $0.state == .chained(nextId: "") }.count
        return Float(accepted) / Float(relevant.count)
    }

    /// Per-type stats for the history view.
    func typeStats() -> [(type: ProactiveSuggestionType, total: Int, accepted: Int, dismissed: Int)] {
        var stats: [ProactiveSuggestionType: (total: Int, accepted: Int, dismissed: Int)] = [:]
        for s in history {
            var current = stats[s.type, default: (0, 0, 0)]
            current.total += 1
            switch s.state {
            case .accepted, .chained: current.accepted += 1
            case .dismissed: current.dismissed += 1
            default: break
            }
            stats[s.type] = current
        }
        return stats.map { ($0.key, $0.value.total, $0.value.accepted, $0.value.dismissed) }
            .sorted { $0.total > $1.total }
    }
}
